create database grocery_store;
use grocery_store;

CREATE TABLE supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

CREATE TABLE categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

CREATE TABLE employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

CREATE TABLE customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

CREATE TABLE products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2)
);

CREATE TABLE orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255)
);

CREATE TABLE order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2)
);

SELECT * FROM products;
SELECT * FROM order_details;
select * from  employees;
select * from categories;
select * from customers;
select * from orders;
select * from supplier;

ALTER TABLE products
ADD CONSTRAINT fk_sup FOREIGN KEY (sup_id) REFERENCES supplier(sup_id),
ADD CONSTRAINT fk_cat FOREIGN KEY (cat_id) REFERENCES categories(cat_id);

ALTER TABLE orders
ADD CONSTRAINT fk_cust FOREIGN KEY (cust_id) REFERENCES customers(cust_id),
ADD CONSTRAINT fk_emp FOREIGN KEY (emp_id) REFERENCES employees(emp_id);

ALTER TABLE order_details
ADD CONSTRAINT fk_ord FOREIGN KEY (ord_id) REFERENCES orders(ord_id),
ADD CONSTRAINT fk_prod FOREIGN KEY (prod_id) REFERENCES products(prod_id);


-- Analysis Questions

-- 1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.

-- How many unique customers have placed orders?
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM orders;

-- Which customers have placed the highest number of orders?
SELECT 
    c.cust_id,
    c.cust_name,
    COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_orders DESC;

-- What is the total and average purchase value per customer?
SELECT 
    c.cust_id,c.cust_name,
    SUM(od.total_price) AS total_purchase,
    SUM(od.total_price) / COUNT(DISTINCT o.ord_id) AS avg_purchase
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name;

-- Who are the top 5 customers by total purchase amount?
SELECT 
    c.cust_id,
    c.cust_name,
    SUM(od.total_price) AS total_purchase
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase DESC
LIMIT 5;

-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.

-- How many products exist in each category?
SELECT 
    c.cat_name,
    COUNT(p.prod_id) AS total_products
FROM categories c
LEFT JOIN products p ON c.cat_id = p.cat_id
GROUP BY c.cat_name;

-- What is the average price of products by category?
SELECT 
    c.cat_name,
    AVG(p.price) AS avg_price
FROM categories c
JOIN products p ON c.cat_id = p.cat_id
GROUP BY c.cat_name;

-- Which products have the highest total sales volume (by quantity)?
SELECT 
    p.prod_id,
    p.prod_name,
    SUM(od.quantity) AS total_quantity
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_quantity DESC;

-- What is the total revenue generated by each product?
SELECT 
    p.prod_id,
    p.prod_name,
    SUM(od.total_price) AS total_revenue
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name;

-- How do product sales vary by category and supplier?
SELECT 
    c.cat_name,
    s.sup_name,
    SUM(od.total_price) AS total_sales
FROM order_details od
JOIN products p ON od.prod_id = p.prod_id
JOIN categories c ON p.cat_id = c.cat_id
JOIN supplier s ON p.sup_id = s.sup_id
GROUP BY c.cat_name, s.sup_name;

-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.

-- How many orders have been placed in total?
SELECT COUNT(*) AS total_orders
FROM orders;

-- What is the average value per order?
SELECT AVG(order_total) AS avg_order_value
FROM (
    SELECT ord_id, SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) t;

-- On which dates were the most orders placed?
SELECT 
    order_date,
    COUNT(*) AS total_orders
FROM orders
GROUP BY order_date
ORDER BY total_orders DESC;

-- What are the monthly trends in order volume and revenue?
SELECT 
    DATE_FORMAT(STR_TO_DATE(order_date, '%d/%m/%Y'), '%Y/%m') AS month,
    COUNT(DISTINCT o.ord_id) AS total_orders,
    SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY DATE_FORMAT(STR_TO_DATE(order_date, '%d/%m/%Y'), '%Y/%m')
ORDER BY month;


-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.

-- How many suppliers are there in the database?
SELECT COUNT(*) AS total_suppliers
FROM supplier;

-- Which supplier provides the most products?
SELECT 
    s.sup_id,
    s.sup_name,
    COUNT(p.prod_id) AS total_products
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_products DESC;

-- What is the average price of products from each supplier?
SELECT 
    s.sup_name,
    AVG(p.price) AS avg_price
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_name;

-- Which suppliers contribute the most to total product sales (by revenue)?
SELECT 
    s.sup_name,
    SUM(od.total_price) AS total_revenue
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY s.sup_name
ORDER BY total_revenue DESC;

-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.

-- How many employees have processed orders?
SELECT COUNT(DISTINCT emp_id) AS active_employees
FROM orders;

-- Which employees have handled the most orders?
SELECT 
    e.emp_id,
    e.emp_name,
    COUNT(o.ord_id) AS total_orders
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_orders DESC;

-- What is the total sales value processed by each employee?
SELECT 
    e.emp_name,
    SUM(od.total_price) AS total_sales
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_name;

-- What is the average order value handled per employee?
SELECT 
    e.emp_name,
    AVG(t.order_total) AS avg_order_value
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN (
    SELECT ord_id, SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) t ON o.ord_id = t.ord_id
GROUP BY e.emp_name;

-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.

-- What is the relationship between quantity ordered and total price?
SELECT quantity, total_price
FROM order_details;

-- What is the average quantity ordered per product?
SELECT 
    p.prod_name,
    AVG(od.quantity) AS avg_quantity
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name;

-- How does the unit price vary across products and orders?
SELECT 
    p.prod_name,
    AVG(od.each_price) AS avg_price,
    MIN(od.each_price) AS min_price,
    MAX(od.each_price) AS max_price
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name;





